Update CI/CD workflow

diff --git a/.github/workflows/check-contracts-and-assets.yml b/.github/workflows/check-contracts-and-assets.yml
--- a/.github/workflows/check-contracts-and-assets.yml
+++ b/.github/workflows/check-contracts-and-assets.yml
@@ -7,38 +7,38 @@ permissions:
   # Required to post messages to the PR
   pull-requests: write
 jobs:
-  validate-data-contracts:
-    runs-on: ubuntu-latest
-    name: 'Validate Data Contracts'
-    steps:    
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      # By default, the Gable CLI will exit with a non-zero exit code if no contracts are found when calling the
-      # validate or publish command. For this tutorial, there won't be any contracts in the repo to start, so we
-      # need this extra step to check if we should skip validation
-      - name: Check if Contracts Exist
-        shell: bash
-        run: |
-          set +e
-          sh -c "ls ./contracts/*.yaml"
-          if [ $? -eq 0 ]; then
-              echo "Found contract files, running validation..."
-          else
-              echo "No contract files found, skipping contract validation..."
-              echo SKIP_VALIDATION=true >> $GITHUB_ENV
-          fi
-      - name: Validate Contracts
-        if: ${{ env.SKIP_VALIDATION  != 'true' }}
-        uses: gabledata/cicd/github-actions/validate-contracts@main
-        with:
-          # Provide API key secret, and endpoint variable created in previous steps
-          gable-api-key: ${{secrets.SST_API_KEY}}
-          gable-api-endpoint: ${{secrets.SST_API_ENDPOINT}}
-          # List of paths to contract files that should be validated, with support for glob syntax.
-          # Can either be specified as a space separated list ('contract1.yml contract2.yml'), or
-          # a multiline string
-          contract-paths: |
-            ./contracts/*.yaml
+  # validate-data-contracts:
+  #   runs-on: ubuntu-latest
+  #   name: 'Validate Data Contracts'
+  #   steps:    
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v3
+  #     # By default, the Gable CLI will exit with a non-zero exit code if no contracts are found when calling the
+  #     # validate or publish command. For this tutorial, there won't be any contracts in the repo to start, so we
+  #     # need this extra step to check if we should skip validation
+  #     - name: Check if Contracts Exist
+  #       shell: bash
+  #       run: |
+  #         set +e
+  #         sh -c "ls ./contracts/*.yaml"
+  #         if [ $? -eq 0 ]; then
+  #             echo "Found contract files, running validation..."
+  #         else
+  #             echo "No contract files found, skipping contract validation..."
+  #             echo SKIP_VALIDATION=true >> $GITHUB_ENV
+  #         fi
+  #     - name: Validate Contracts
+  #       if: ${{ env.SKIP_VALIDATION  != 'true' }}
+  #       uses: gabledata/cicd/github-actions/validate-contracts@main
+  #       with:
+  #         # Provide API key secret, and endpoint variable created in previous steps
+  #         gable-api-key: ${{secrets.SST_API_KEY}}
+  #         gable-api-endpoint: ${{secrets.SST_API_ENDPOINT}}
+  #         # List of paths to contract files that should be validated, with support for glob syntax.
+  #         # Can either be specified as a space separated list ('contract1.yml contract2.yml'), or
+  #         # a multiline string
+  #         contract-paths: |
+  #           ./contracts/*.yaml
   check-data-assets-against-contracts:
     runs-on: ubuntu-latest
     name: 'Check Data Assets Against Contracts'
